### text/html
http://localhost:3000/api/hi

### json
http://localhost:3000/api/hi-json

### trpc
GET http://localhost:3000/api/trpc/user.getUserById?input="0001"

# curl 'http://localhost:3000/api/trpc-ws' -H 'Upgrade: websocket' -H 'Connection: Upgrade' --verbose
### trpc-ws
WS ws://localhost:3000/api/trpc-ws
# input="bbWS"
# {{@streaming
#   async function writeStream(){
#     await sleep(10000);
#     $requestClient.send({
#       "event": "ping",
#       "reqid": 45
#     });
#     await sleep(1000);
#   }
#   exports.waitPromise = writeStream();
# }}